# Generated by Django 4.2.13 on 2024-06-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="gratudated_date",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
