# Generated by Django 4.2.13 on 2024-06-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0002_certificate_gratudated_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificate",
            options={"ordering": ("-gratudated_date",)},
        ),
    ]
