# Generated by Django 4.2.13 on 2024-06-25 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0003_alter_certificate_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="description",
        ),
    ]
