# Generated by Django 4.2.13 on 2024-06-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0004_remove_certificate_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("link", models.URLField()),
                ("completion_date", models.DateField()),
            ],
            options={
                "ordering": ("-completion_date",),
            },
        ),
    ]
