# Generated by Django 4.2.13 on 2024-06-25 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0005_project"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificate",
            options={},
        ),
    ]
