# Generated by Django 4.2.13 on 2024-06-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0008_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=254)),
            ],
        ),
    ]
