# Generated by Django 4.2.13 on 2024-06-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0010_education"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
            ],
        ),
    ]
