# Generated by Django 4.2.13 on 2024-06-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0011_tools"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tools",
            new_name="Tool",
        ),
    ]
